In [36]:
import pandas as pd
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression




In [37]:
train_data = pd.DataFrame(pd.read_excel('Data_Train.xlsx'))
train_data.head()


Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [38]:
# test_data = pd.DataFrame(pd.read_excel('Test_set.xlsx'))
# test_data.head()

In [39]:
# combine_dataframe = [train_data, test_data]
# df = pd.concat(combine_dataframe)

In [40]:
# shape of the df

train_data.shape

(10683, 11)

In [41]:
# size of df
train_data.size

117513

In [42]:
# information of dataframe

train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
dtypes: int64(1), object(10)
memory usage: 918.2+ KB


In [43]:
train_data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [44]:
# split date of journey into day, date and year column
train_data[['Day', 'Month', 'Year']] = train_data['Date_of_Journey'].str.split('/', expand=True)
print(train_data)

           Airline Date_of_Journey    Source Destination  \
0           IndiGo      24/03/2019  Banglore   New Delhi   
1        Air India       1/05/2019   Kolkata    Banglore   
2      Jet Airways       9/06/2019     Delhi      Cochin   
3           IndiGo      12/05/2019   Kolkata    Banglore   
4           IndiGo      01/03/2019  Banglore   New Delhi   
...            ...             ...       ...         ...   
10678     Air Asia       9/04/2019   Kolkata    Banglore   
10679    Air India      27/04/2019   Kolkata    Banglore   
10680  Jet Airways      27/04/2019  Banglore       Delhi   
10681      Vistara      01/03/2019  Banglore   New Delhi   
10682    Air India       9/05/2019     Delhi      Cochin   

                       Route Dep_Time  Arrival_Time Duration Total_Stops  \
0                  BLR → DEL    22:20  01:10 22 Mar   2h 50m    non-stop   
1      CCU → IXR → BBI → BLR    05:50         13:15   7h 25m     2 stops   
2      DEL → LKO → BOM → COK    09:25  04:25 10 Jun

In [45]:
# converting Day, month and year column into integer datatype
train_data[['Day', 'Month', 'Year']] = train_data[['Day', 'Month', 'Year']].astype(int)

In [46]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
 11  Day              10683 non-null  int64 
 12  Month            10683 non-null  int64 
 13  Year             10683 non-null  int64 
dtypes: int64(4), object(10)
memory usage: 1.1+ MB


In [47]:
# Since we have day, month and year in seperate column, we don't need date_of_journey column

train_data.drop(columns='Date_of_Journey', axis=1, inplace=True)

In [48]:
train_data.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

   Arrival_Time Duration Total_Stops Additional_Info  Price  Day  Month  Year  
0  01:10 22 Mar   2h 50m    non-stop         No info   3897   24      3  2019  
1         13:15   7h 25m     2 stops         No info   7662    1      5  2019  
2  04:25 10 Jun      19h     2 stops         No info  13882    9      6  2019  
3         23:30   5h 25m      1 stop         No info   6218   12      5  2019  
4         21:35   4h 45m      1 stop         No info  13302    1      3  2019

In [49]:
# Preprocessing Arrival_time column
train_data['Arrival_Time'] = train_data['Arrival_Time'].str.split(' ').str[0]  #split arrival time and access index[0] i.e arrival_time, we already have month
train_data.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

  Arrival_Time Duration Total_Stops Additional_Info  Price  Day  Month  Year  
0        01:10   2h 50m    non-stop         No info   3897   24      3  2019  
1        13:15   7h 25m     2 stops         No info   7662    1      5  2019  
2        04:25      19h     2 stops         No info  13882    9      6  2019  
3        23:30   5h 25m      1 stop         No info   6218   12      5  2019  
4        21:35   4h 45m      1 stop         No info  13302    1      3  2019

In [50]:
#  Spliting Arrival_time into arrival_hour, arrival_min
train_data[['arrival_hour' , 'arrival_min']] = train_data['Arrival_Time'].str.split(':', expand= True) 

In [51]:
train_data.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

  Arrival_Time Duration Total_Stops Additional_Info  Price  Day  Month  Year  \
0        01:10   2h 50m    non-stop         No info   3897   24      3  2019   
1        13:15   7h 25m     2 stops         No info   7662    1      5  2019   
2        04:25      19h     2 stops         No info  13882    9      6  2019   
3        23:30   5h 25m      1 stop         No info   6218   12      5  2019   
4        21:35   4h 45m      1 stop         No info  13302    1      3  2019   

  arrival_hour arrival_min  
0           01          10  
1           13          15  
2           04          25  
3           23          30  
4           21          35

In [52]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64 
 10  Day              10683 non-null  int64 
 11  Month            10683 non-null  int64 
 12  Year             10683 non-null  int64 
 13  arrival_hour     10683 non-null  object
 14  arrival_min      10683 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.2+ MB


In [53]:
# converting arrival_hour and arrival_min column into integer datatype

train_data[['arrival_hour' , 'arrival_min']] = train_data[['arrival_hour' , 'arrival_min']].astype(int)

In [54]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64 
 10  Day              10683 non-null  int64 
 11  Month            10683 non-null  int64 
 12  Year             10683 non-null  int64 
 13  arrival_hour     10683 non-null  int64 
 14  arrival_min      10683 non-null  int64 
dtypes: int64(6), object(9)
memory usage: 1.2+ MB


In [55]:
# Since we have arrival_hour, arrival_min in seperate column, we don't need Arrival_time column anymore

train_data.drop('Arrival_Time', axis = 1, inplace=True)
train_data.head()

Airline    Source Destination                  Route Dep_Time Duration  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   2h 50m   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   7h 25m   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25      19h   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   5h 25m   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   4h 45m   

  Total_Stops Additional_Info  Price  Day  Month  Year  arrival_hour  \
0    non-stop         No info   3897   24      3  2019             1   
1     2 stops         No info   7662    1      5  2019            13   
2     2 stops         No info  13882    9      6  2019             4   
3      1 stop         No info   6218   12      5  2019            23   
4      1 stop         No info  13302    1      3  2019            21   

   arrival_min  
0           10  
1           15  
2           25  
3           30  
4           35

In [56]:
train_data.shape

(10683, 14)

In [57]:
train_data.isnull().sum()

Airline            0
Source             0
Destination        0
Route              1
Dep_Time           0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
Day                0
Month              0
Year               0
arrival_hour       0
arrival_min        0
dtype: int64

In [58]:
# split dep_time into dep_hour, dep_min
train_data[['Dep_hour', 'Dep_min']] = train_data['Dep_Time'].str.split(':', expand=True)

In [59]:
# converting dep_hour, dep_min into integer data type
train_data[['Dep_hour', 'Dep_min']] = train_data[['Dep_hour', 'Dep_min']].astype(int)

In [60]:
# checking unique on total_stop column
train_data['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [61]:
train_data[train_data['Total_Stops'].isnull()]

Airline Source Destination Route Dep_Time Duration Total_Stops  \
9039  Air India  Delhi      Cochin   NaN    09:45  23h 40m         NaN   

     Additional_Info  Price  Day  Month  Year  arrival_hour  arrival_min  \
9039         No info   7480    6      5  2019             9           25   

      Dep_hour  Dep_min  
9039         9       45

In [62]:
train_data['Total_Stops'].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [63]:
train_data.drop('Route', axis = 1, inplace = True)

In [64]:
# index of null value
train_data[train_data.isnull().any(axis=1)].index

Index([9039], dtype='int64')

In [65]:
train_data.drop('Dep_Time', axis=1, inplace=True)

In [66]:
train_data.isnull().sum()

Airline            0
Source             0
Destination        0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
Day                0
Month              0
Year               0
arrival_hour       0
arrival_min        0
Dep_hour           0
Dep_min            0
dtype: int64

In [67]:
# plt.figure(figsize=[12,7])
# plt.hist(train_data['Price'], bins=15)


In [68]:
x = train_data.drop(columns='Price', axis=1)
y = train_data['Price']

In [69]:
X_train, x_test, Y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)


In [70]:
x_test

Airline    Source Destination Duration Total_Stops  \
6076         Jet Airways   Kolkata    Banglore  12h 30m      1 stop   
3544               GoAir     Delhi      Cochin       9h      1 stop   
7313         Jet Airways   Kolkata    Banglore   5h 45m      1 stop   
5032              IndiGo   Chennai     Kolkata   2h 20m    non-stop   
2483         Jet Airways     Delhi      Cochin   5h 35m      1 stop   
...                  ...       ...         ...      ...         ...   
9797   Multiple carriers     Delhi      Cochin      13h      1 stop   
9871            SpiceJet   Kolkata    Banglore   2h 30m    non-stop   
10063           Air Asia     Delhi      Cochin  14h 30m      1 stop   
7623              IndiGo  Banglore       Delhi   2h 50m    non-stop   
8618         Jet Airways   Kolkata    Banglore  12h 10m      1 stop   

                   Additional_Info  Day  Month  Year  arrival_hour  \
6076   In-flight meal not included   18      5  2019            18   
3544                       No info    3      6  2019            19   
7313                       No info    1      5  2019            19   
5032                       No info   24      5  2019            17   
2483   In-flight meal not included   21      5  2019             4   
...                            ...  ...    ...   ...           ...   
9797                       No info   27      6  2019            21   
9871                       No info    6      3  2019            19   
10063                      No info   21      4  2019            22   
7623                       No info    9      4  2019            11   
8618                       No info    9      6  2019             4   

       arrival_min  Dep_hour  Dep_min  
6076            15         5       45  
3544            35        10       35  
7313            50        14        5  
5032             5        14       45  
2483            25        22       50  
...            ...       ...      ...  
9797             0         8        0  
9871            45        17       15  
10063           25         7       55  
7623            20         8       30  
8618            40        16       30  

[2137 rows x 13 columns]

In [71]:
x_train_simple = X_train['Year'].values.reshape(-1,1)
x_test_simpole = x_test['Year'].values.reshape(-1,1)
Y_train

8990    23528
3684    12373
1034     5583
3909     7695
3088    11972
        ...  
5734    12242
5191    10844
5390     7670
860      6144
7270    10262
Name: Price, Length: 8546, dtype: int64

In [72]:
simple_lr = LinearRegression()
simple_lr.fit(x_train_simple, Y_train)

LinearRegression()

In [73]:
y_hat = simple_lr.predict(x_test_simpole)
y_hat[:5]

array([9074.82787269, 9074.82787269, 9074.82787269, 9074.82787269,
       9074.82787269])

In [74]:
simple_lr.coef_

array([0.])

In [75]:
simple_lr.intercept_

9074.827872688977

In [76]:
# # plot
# plt.figure(figsize=(12.6))
# sns.regplot(x = 'Year', y = 'Price', data= df)
# plt.show()

Prediction from multiple features

In [77]:
# Taking multiple columns
to_select = ['Day', 'Month', 'Year', 'arrival_hour', 'arrival_min', 'Dep_hour', 'Dep_min']



In [78]:
x_train_multi = X_train[to_select].values
x_test_multi =  x_test[to_select].values


In [79]:
multi_lr = LinearRegression()
multi_lr.fit(x_train_multi, Y_train)

LinearRegression()

In [81]:
y_pred_multi = multi_lr.predict(x_test_multi)
y_pred_multi[:5]

array([8605.29958459, 8977.04096041, 9535.7838826 , 8447.25045853,
       8035.72082299])

In [82]:
# coffecient
multi_lr.coef_

array([-8.52414061e+01, -4.83745065e+02, -1.13686838e-13,  8.45453973e+00,
       -2.86872542e+01,  8.33125648e+00, -1.00499611e+01])

In [83]:
# intercept 
multi_lr.intercept_


13247.089280940829