In [15]:
import numpy as np


In [74]:
oned_arrar = [1, 2, 3]
arrL = np.array(oned_arrar, dtype='int')
print(type(arrL))

<class 'numpy.ndarray'>


In [22]:
twoD_array = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(twoD_array, dtype='float32')
arr2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [26]:
np.zeros(10, dtype="float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [28]:
np.ones([3, 2], dtype="float")

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.full([3, 5], 33)

array([[33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33]])

In [34]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
# random 3*3 matrix
np.random.random((3, 3))

array([[0.77785805, 0.30910312, 0.45540933],
       [0.7289553 , 0.31553812, 0.57125405],
       [0.70795016, 0.16139669, 0.81002773]])

In [57]:
# specifying the range
np.random.normal(0,2, [3,3]) #float data

array([[-0.43466955, -3.24421064,  0.35018229],
       [ 2.9046446 ,  0.97853791, -1.25158625],
       [ 0.28829551,  0.9381008 ,  3.58962504]])

In [58]:
np.random.randint(0,10, [3,3])

array([[1, 7, 7],
       [3, 6, 1],
       [4, 6, 8]])

In [68]:
sam_arr = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(f'The dimension of the arrary is {sam_arr.ndim}')

The dimension of the arrary is 3


In [69]:
sam_arr.shape

(1, 3, 3)

In [70]:
sam_arr.size

9

In [72]:
sam_arr.dtype

dtype('int32')