In [2]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# np.reshape(arr, (4, 3))
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
# 3d
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [17]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr1.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

This process raise an exception, since there are 8 elements before reshaping and 9 elements after reshaping.
For reshaping to happen

In [19]:
array1 = np.array([1,1,1])
array2 = np.array([2,2,2])

concat_arr = np.concatenate((array1,array2))
concat_arr

array([1, 1, 1, 2, 2, 2])

In [23]:
arr_2d = np.array([[1, 1, 1],[2,2,2]])
arr_2d_1 = np.array([
    [9,9,9],
    [10,10,10]
])

np.concatenate((arr_2d, arr_2d_1), axis=0)

array([[ 1,  1,  1],
       [ 2,  2,  2],
       [ 9,  9,  9],
       [10, 10, 10]])

In [26]:
arr_2d = np.array([[1, 1, 1],[2,2,2]])
arr_2d_1 = np.array([
    [9,9,9],
    [10,10,10]
])

np.concatenate((arr_2d, arr_2d_1), axis=1)

array([[ 1,  1,  1,  9,  9,  9],
       [ 2,  2,  2, 10, 10, 10]])

In [33]:
# splitting above array 
np.split(arr1, 2)

# np.array_split(arr1, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]

In [41]:
split_2d_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.array_split(split_2d_array, 2)
# np.split(split_2d_array, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [40]:
split_2d_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.array_split(split_2d_array, 2, axis=1)
# np.split(split_2d_array, 2)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [48]:
import time

x1 = np.arange(1, 100000)
x2 = np.arange(1, 100000)

mul = np.zeros(x1.shape)
mul

array([0., 0., 0., ..., 0., 0., 0.])

In [49]:
start_time = time.process_time()
for i in range(len(x1)):
    mul[i]= x1[i] * x2[i]
end_time = time.process_time()

print(end_time - start_time)

0.140625


C:\Users\Dell\AppData\Local\Temp\ipykernel_17264\2181096159.py:3: RuntimeWarning: overflow encountered in scalar multiply
  mul[i]= x1[i] * x2[i]


In [50]:
a = np.array([1,2,3])
b = 2

print(a + b)

[3 4 5]


In [52]:
x = np.array([1,2,3])
y = np.array([
    [10],
    [20],
    [30]
])
print(f'Shape of a: {x.shape}')
print(f'Shape of a: {y.shape}')

print(x+y)

Shape of a: (3,)
Shape of a: (3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
